### PR TITLE
Parse constraints not separated by comma

### PR DESCRIPTION
**Pull request by Mateiadrielrafael**
I messed up the source branch for #47 and could not figure out how to change it, so I closed that PR and opened this one instead.

### CODE REVIEW

**Comment by JakeWheat** [comment]
Great, thanks.

I'm planning to do some drastic changes in the next few days to make the code a bit more modern. I've already planned out switching from lhs to hs, switching the pretty printing library to prettyprinter, and switching the code so that it parses from and pretty prints to Lazy Text.

Then I'll try to finish some megaparsec investigation on separate lexing and source positions, and switch to megaparsec, then after that switch remaining uses of String to Text - mainly in the Syntax.

Let me know if you have any thoughts or think any of it's a bad idea.

**Comment by ad-si** [comment]
@JakeWheat Sounds awesome! Looking forward to it! 😊
- I guess that's the one you mean anyways, but [github.com/quchen/prettyprinter](https://github.com/quchen/prettyprinter) has been the best pretty printer of the ones I tested.
- The opinions on Lazy Text don't seem to be conclusive. Not sure if its a good pick for this project: https://stackoverflow.com/questions/24641540. But using Text instead of String is definitely a big win!
- Megaparsec sounds like a good choice!

**Comment by JakeWheat** [comment]
@ad-si 
I took your advice on strict Text. The new version is ready to check out, a couple of minor issues I hope to fix today with the pretty printer formating, and the rendering of the test case examples on the website.

**Comment by Mateiadrielrafael** [comment]
> @ad-si 
> I took your advice on strict Text. The new version is ready to check out, a couple of minor issues I hope to fix today with the pretty printer formating, and the rendering of the test case examples on the website.

That's awesome!

**Pull request merged**
